### PR TITLE
fix: decouple schema from db config

### LINKED ISSUE #3: fix: initialize database config in a schema file
This change will move the creation of our tables into a `schema.sql` file to reduce the size of our database configuration file `db.go`.  All of the tables will be defined in the schema file and the file will be read and executed by the MySQL driver.

### PR DESCRIPTION
**Pull request by villaleo**
This change closes #3 . It moves the schema config to a new file, `db/schema.sql`.

In addition, the project's module was also renamed from `github.com/villaleo/somos-events` to `github.com/somos831/somos-backend`.

### CODE REVIEW

File: cmd/main.go [hunk 1]
```diff
@@ -18,11 +18,11 @@ func main() {
 
 	dbUser := os.Getenv("DB_USER")
 	dbPassword := os.Getenv("DB_PASSWORD")
-	dbName := os.Getenv("DB_NAME")
-
```
Comment (garcialuis) [inline cmd/main.go:22]: I would rather continue using the env var instead of hard coding the db name.

**Review by garcialuis — CHANGES_REQUESTED** [review]
Just had one thing that should be updated, the rest looks good.

Using the sql file instead of having the queries in the code is a step in the right direction :). I'll open a PR soon to add migrations so that we can track db changes. 
And thanks for updating the dependencies!

File: cmd/main.go (hunk 1 above)
Comment (villaleo) [reply cmd/main.go:22]: Thanks for the feedback! I will reintroduce the environment variable `DB_NAME`.

**Review by garcialuis — APPROVED** [review]
